SECTION "Pics 1", ROMX

SlowbroPicFront::          INCBIN "gfx/pokemon/front/slowbro.pic"
UnusedPics1Data41EA::      INCBIN "gfx/pokemon/unused/pics1_41ea_4201.bin"

RhydonPicBack::            INCBIN "gfx/pokemon/back/rhydonb.pic"

ArcaninePicFront::         INCBIN "gfx/pokemon/front/arcanine.pic"
UnusedPics1Data449C::      INCBIN "gfx/pokemon/unused/pics1_449c_44a5.bin"

KangaskhanPicBack::        INCBIN "gfx/pokemon/back/kangaskhanb.pic"

NidoranMPicFront::         INCBIN "gfx/pokemon/front/nidoranm.pic"
UnusedPics1Data461D::      INCBIN "gfx/pokemon/unused/pics1_461d_4622.bin"

NidoranMPicBack::          INCBIN "gfx/pokemon/back/nidoranmb.pic"

ClefairyPicFront::         INCBIN "gfx/pokemon/front/clefairy.pic"
UnusedPics1Data476B::      INCBIN "gfx/pokemon/unused/pics1_476b_4784.bin"

ClefairyPicBack::          INCBIN "gfx/pokemon/back/clefairyb.pic"

SpearowPicFront::          INCBIN "gfx/pokemon/front/spearow.pic"
UnusedPics1Data48A9::      INCBIN "gfx/pokemon/unused/pics1_48a9_48c1.bin"

SpearowPicBack::           INCBIN "gfx/pokemon/back/spearowb.pic"

VoltorbPicFront::          INCBIN "gfx/pokemon/front/voltorb.pic"
UnusedPics1Data498D::      INCBIN "gfx/pokemon/unused/pics1_498d_4999.bin"

VoltorbPicBack::           INCBIN "gfx/pokemon/back/voltorbb.pic"

KangaskhanPicFront::       INCBIN "gfx/pokemon/front/kangaskhan.pic"
UnusedPics1Data4C4F::      INCBIN "gfx/pokemon/unused/pics1_4c4f_4c5f.bin"

NidokingPicBack::          INCBIN "gfx/pokemon/back/nidokingb.pic"

NidokingPicFront::         INCBIN "gfx/pokemon/front/nidoking.pic"
UnusedPics1Data4F36::      INCBIN "gfx/pokemon/unused/pics1_4f36_4f86.bin"

SlowbroPicBack::           INCBIN "gfx/pokemon/back/slowbrob.pic"

IvysaurPicFront::          INCBIN "gfx/pokemon/front/ivysaur.pic"
UnusedPics1Data514B::      INCBIN "gfx/pokemon/unused/pics1_514b_5156.bin"

IvysaurPicBack::           INCBIN "gfx/pokemon/back/ivysaurb.pic"

LaprasPicFront::           INCBIN "gfx/pokemon/front/lapras.pic"
UnusedPics1Data539F::      INCBIN "gfx/pokemon/unused/pics1_539f_53f7.bin"

ExeggutorPicBack::         INCBIN "gfx/pokemon/back/exeggutorb.pic"

LickitungPicFront::        INCBIN "gfx/pokemon/front/lickitung.pic"
UnusedPics1Data563B::      INCBIN "gfx/pokemon/unused/pics1_563b_563d.bin"

LickitungPicBack::         INCBIN "gfx/pokemon/back/lickitungb.pic"

ExeggcutePicFront::        INCBIN "gfx/pokemon/front/exeggcute.pic"
UnusedPics1Data5896::      INCBIN "gfx/pokemon/unused/pics1_5896_58ef.bin"

ExeggcutePicBack::         INCBIN "gfx/pokemon/back/exeggcuteb.pic"

GrimerPicFront::           INCBIN "gfx/pokemon/front/grimer.pic"
UnusedPics1Data5A8E::      INCBIN "gfx/pokemon/unused/pics1_5a8e_5aaf.bin"

GrimerPicBack::            INCBIN "gfx/pokemon/back/grimerb.pic"

GengarPicFront::           INCBIN "gfx/pokemon/front/gengar.pic"
UnusedPics1Data5C74::      INCBIN "gfx/pokemon/unused/pics1_5c74_5cc5.bin"

GengarPicBack::            INCBIN "gfx/pokemon/back/gengarb.pic"

NidoranFPicFront::         INCBIN "gfx/pokemon/front/nidoranf.pic"
UnusedPics1Data5DBF::      INCBIN "gfx/pokemon/unused/pics1_5dbf_5dc1.bin"

NidoranFPicBack::          INCBIN "gfx/pokemon/back/nidoranfb.pic"

RhydonPicFront::           INCBIN "gfx/pokemon/front/rhydon.pic"
UnusedPics1Data5FDF::      INCBIN "gfx/pokemon/unused/pics1_5fdf_5fee.bin"

NidoqueenPicBack::         INCBIN "gfx/pokemon/back/nidoqueenb.pic"

CubonePicFront::           INCBIN "gfx/pokemon/front/cubone.pic"
UnusedPics1Data6181::      INCBIN "gfx/pokemon/unused/pics1_6181_6195.bin"

CubonePicBack::            INCBIN "gfx/pokemon/back/cuboneb.pic"

RhyhornPicFront::          INCBIN "gfx/pokemon/front/rhyhorn.pic"
UnusedPics1Data637C::      INCBIN "gfx/pokemon/unused/pics1_637c_640e.bin"

RhyhornPicBack::           INCBIN "gfx/pokemon/back/rhyhornb.pic"

ExeggutorPicFront::        INCBIN "gfx/pokemon/front/exeggutor_intense_indigo.bin"
UnusedPics1Data666B::      INCBIN "gfx/pokemon/unused/pics1_666b_667b.bin"

LaprasPicBack::            INCBIN "gfx/pokemon/back/laprasb.pic"

NidoqueenPicFront::        INCBIN "gfx/pokemon/front/nidoqueen.pic"
UnusedPics1Data6928::      INCBIN "gfx/pokemon/unused/pics1_6928_693c.bin"

ArcaninePicBack::          INCBIN "gfx/pokemon/back/arcanineb.pic"

GyaradosPicFront::         INCBIN "gfx/pokemon/front/gyarados.pic"
UnusedPics1Data6C1B::      INCBIN "gfx/pokemon/unused/pics1_6c1b_6c24.bin"

GyaradosPicBack::          INCBIN "gfx/pokemon/back/gyaradosb.pic"

ShellderPicFront::         INCBIN "gfx/pokemon/front/shellder.pic"
UnusedPics1Data6DBA::      INCBIN "gfx/pokemon/unused/pics1_6dba_6dc2.bin"

ShellderPicBack::          INCBIN "gfx/pokemon/back/shellderb.pic"

TentacoolPicFront::        INCBIN "gfx/pokemon/front/tentacool.pic"
UnusedPics1Data6EFE::      INCBIN "gfx/pokemon/unused/pics1_6efe_6f1b.bin"

TentacoolPicBack::         INCBIN "gfx/pokemon/back/tentacoolb.pic"

GastlyPicFront::           INCBIN "gfx/pokemon/front/gastly.pic"
UnusedPics1Data70B3::      INCBIN "gfx/pokemon/unused/pics1_70b3_718f.bin"

GastlyPicBack::            INCBIN "gfx/pokemon/back/gastlyb.pic"

ScytherPicFront::          INCBIN "gfx/pokemon/front/scyther.pic"
UnusedPics1Data7426::      INCBIN "gfx/pokemon/unused/pics1_7426_743b.bin"

ScytherPicBack::           INCBIN "gfx/pokemon/back/scytherb.pic"

StaryuPicFront::           INCBIN "gfx/pokemon/front/staryu.pic"

StaryuPicBack::            INCBIN "gfx/pokemon/back/staryub.pic"

BlastoisePicFront::        INCBIN "gfx/pokemon/front/blastoise.pic"
UnusedPics1Data7848::      INCBIN "gfx/pokemon/unused/pics1_7848_7850.bin"

BlastoisePicBack::         INCBIN "gfx/pokemon/back/blastoiseb.pic"

PinsirPicFront::           INCBIN "gfx/pokemon/front/pinsir.pic"
UnusedPics1Data7A61::      INCBIN "gfx/pokemon/unused/pics1_7a61_7aa9.bin"

PinsirPicBack::            INCBIN "gfx/pokemon/back/pinsirb.pic"

TangelaPicFront::          INCBIN "gfx/pokemon/front/tangela.pic"
UnusedPics1Data7C89::      INCBIN "gfx/pokemon/unused/pics1_7c89_7ce6.bin"

TangelaPicBack::           INCBIN "gfx/pokemon/back/tangelab.pic"


SECTION "Pics 2", ROMX

GrowlithePicFront::          INCBIN "gfx/pokemon/exact/pics2_4000_growlithepicfront.bin"
                             INCBIN "gfx/pokemon/unused/pics2_40f2_4100.bin"
GrowlithePicBack::           INCBIN "gfx/pokemon/back/growlitheb.pic"
OnixPicFront::               INCBIN "gfx/pokemon/exact/pics2_4164_onixpicfront.bin"
                             INCBIN "gfx/pokemon/unused/pics2_42f1_42ff.bin"
OnixPicBack::                INCBIN "gfx/pokemon/exact/pics2_4300_onixpicback.bin"
                             INCBIN "gfx/pokemon/unused/pics2_4382_4382.bin"
FearowPicFront::             INCBIN "gfx/pokemon/exact/pics2_4383_fearowpicfront.bin"
                             INCBIN "gfx/pokemon/unused/pics2_4526_4528.bin"
FearowPicBack::              INCBIN "gfx/pokemon/exact/pics2_4529_fearowpicback.bin"
                             INCBIN "gfx/pokemon/unused/pics2_45a6_45a6.bin"
PidgeyPicFront::             INCBIN "gfx/pokemon/exact/pics2_45a7_pidgeypicfront.bin"
                             INCBIN "gfx/pokemon/unused/pics2_465a_465a.bin"
PidgeyPicBack::              INCBIN "gfx/pokemon/exact/pics2_465b_pidgeypicback.bin"
                             INCBIN "gfx/pokemon/unused/pics2_469f_469f.bin"
SlowpokePicFront::           INCBIN "gfx/pokemon/exact/pics2_46a0_slowpokepicfront.bin"
                             INCBIN "gfx/pokemon/unused/pics2_47a7_47c1.bin"
SlowpokePicBack::            INCBIN "gfx/pokemon/exact/pics2_47c2_slowpokepicback.bin"
                             INCBIN "gfx/pokemon/unused/pics2_482e_482f.bin"
KadabraPicFront::            INCBIN "gfx/pokemon/exact/pics2_4830_kadabrapicfront.bin"
                             INCBIN "gfx/pokemon/unused/pics2_49b3_49b8.bin"
KadabraPicBack::             INCBIN "gfx/pokemon/exact/pics2_49b9_kadabrapicback.bin"
                             INCBIN "gfx/pokemon/unused/pics2_4a4b_4a4b.bin"
GravelerPicFront::           INCBIN "gfx/pokemon/exact/pics2_4a4c_gravelerpicfront.bin"
                             INCBIN "gfx/pokemon/unused/pics2_4bd1_4bff.bin"
GravelerPicBack::            INCBIN "gfx/pokemon/exact/pics2_4c00_gravelerpicback.bin"
                             INCBIN "gfx/pokemon/unused/pics2_4cad_4cad.bin"
ChanseyPicFront::            INCBIN "gfx/pokemon/exact/pics2_4cae_chanseypicfront.bin"
                             INCBIN "gfx/pokemon/unused/pics2_4dfb_4e20.bin"
ChanseyPicBack::             INCBIN "gfx/pokemon/exact/pics2_4e21_chanseypicback.bin"
                             INCBIN "gfx/pokemon/unused/pics2_4e84_4e84.bin"
MachokePicFront::            INCBIN "gfx/pokemon/exact/pics2_4e85_machokepicfront.bin"
                             INCBIN "gfx/pokemon/unused/pics2_5040_5062.bin"
MachokePicBack::             INCBIN "gfx/pokemon/back/machokeb.pic"
MrMimePicFront::             INCBIN "gfx/pokemon/exact/pics2_50f3_mrmimepicfront.bin"
                             INCBIN "gfx/pokemon/unused/pics2_523e_5246.bin"
MrMimePicBack::              INCBIN "gfx/pokemon/back/mr.mimeb.pic"
HitmonleePicFront::          INCBIN "gfx/pokemon/front/hitmonlee.pic"
                             INCBIN "gfx/pokemon/unused/pics2_5446_545d.bin"
HitmonleePicBack::           INCBIN "gfx/pokemon/exact/pics2_545e_hitmonleepicback.bin"
                             INCBIN "gfx/pokemon/unused/pics2_54bb_54bb.bin"
HitmonchanPicFront::         INCBIN "gfx/pokemon/exact/pics2_54bc_hitmonchanpicfront.bin"
                             INCBIN "gfx/pokemon/unused/pics2_55a5_5642.bin"
HitmonchanPicBack::          INCBIN "gfx/pokemon/exact/pics2_5643_hitmonchanpicback.bin"
                             INCBIN "gfx/pokemon/unused/pics2_56b3_56b3.bin"
ArbokPicFront::              INCBIN "gfx/pokemon/exact/pics2_56b4_arbokpicfront.bin"
                             INCBIN "gfx/pokemon/unused/pics2_5890_5910.bin"
ArbokPicBack::               INCBIN "gfx/pokemon/back/arbokb.pic"
ParasectPicFront::           INCBIN "gfx/pokemon/exact/pics2_59a8_parasectpicfront.bin"
                             INCBIN "gfx/pokemon/unused/pics2_5b1a_5b8b.bin"
ParasectPicBack::            INCBIN "gfx/pokemon/exact/pics2_5b8c_parasectpicback.bin"
                             INCBIN "gfx/pokemon/unused/pics2_5c09_5c09.bin"
PsyduckPicFront::            INCBIN "gfx/pokemon/exact/pics2_5c0a_psyduckpicfront.bin"
                             INCBIN "gfx/pokemon/unused/pics2_5cf0_5d3d.bin"
PsyduckPicBack::             INCBIN "gfx/pokemon/exact/pics2_5d3e_psyduckpicback.bin"
                             INCBIN "gfx/pokemon/unused/pics2_5da8_5da8.bin"
DrowzeePicFront::            INCBIN "gfx/pokemon/front/drowzee.pic"
                             INCBIN "gfx/pokemon/unused/pics2_5f02_5f04.bin"
DrowzeePicBack::             INCBIN "gfx/pokemon/exact/pics2_5f05_drowzeepicback.bin"
                             INCBIN "gfx/pokemon/unused/pics2_5f73_5f73.bin"
GolemPicFront::              INCBIN "gfx/pokemon/exact/pics2_5f74_golempicfront.bin"
                             INCBIN "gfx/pokemon/unused/pics2_60e2_60f1.bin"
GolemPicBack::               INCBIN "gfx/pokemon/exact/pics2_60f2_golempicback.bin"
                             INCBIN "gfx/pokemon/unused/pics2_6160_6160.bin"
MagmarPicFront::             INCBIN "gfx/pokemon/exact/pics2_6161_magmarpicfront.bin"
                             INCBIN "gfx/pokemon/unused/pics2_62bd_62be.bin"
MagmarPicBack::              INCBIN "gfx/pokemon/back/magmarb.pic"
ElectabuzzPicFront::         INCBIN "gfx/pokemon/front/electabuzz.pic"
                             INCBIN "gfx/pokemon/unused/pics2_64eb_64ee.bin"
ElectabuzzPicBack::          INCBIN "gfx/pokemon/exact/pics2_64ef_electabuzzpicback.bin"
                             INCBIN "gfx/pokemon/unused/pics2_6587_6587.bin"
MagnetonPicFront::           INCBIN "gfx/pokemon/exact/pics2_6588_magnetonpicfront.bin"
                             INCBIN "gfx/pokemon/unused/pics2_66f6_6722.bin"
MagnetonPicBack::            INCBIN "gfx/pokemon/exact/pics2_6723_magnetonpicback.bin"
                             INCBIN "gfx/pokemon/unused/pics2_67a5_67a5.bin"
KoffingPicFront::            INCBIN "gfx/pokemon/front/koffing.pic"
                             INCBIN "gfx/pokemon/unused/pics2_6922_6973.bin"
KoffingPicBack::             INCBIN "gfx/pokemon/exact/pics2_6974_koffingpicback.bin"
                             INCBIN "gfx/pokemon/unused/pics2_6a10_6a10.bin"
MankeyPicFront::             INCBIN "gfx/pokemon/front/mankey.pic"
                             INCBIN "gfx/pokemon/unused/pics2_6b07_6b15.bin"
MankeyPicBack::              INCBIN "gfx/pokemon/exact/pics2_6b16_mankeypicback.bin"
                             INCBIN "gfx/pokemon/unused/pics2_6b82_6b83.bin"
SeelPicFront::               INCBIN "gfx/pokemon/exact/pics2_6b84_seelpicfront.bin"
                             INCBIN "gfx/pokemon/unused/pics2_6cd5_6ce7.bin"
SeelPicBack::                INCBIN "gfx/pokemon/exact/pics2_6ce8_seelpicback.bin"
                             INCBIN "gfx/pokemon/unused/pics2_6d32_6d32.bin"
DiglettPicFront::            INCBIN "gfx/pokemon/front/diglett.pic"
                             INCBIN "gfx/pokemon/unused/pics2_6dd5_6e0f.bin"
DiglettPicBack::             INCBIN "gfx/pokemon/back/diglettb.pic"
TaurosPicFront::             INCBIN "gfx/pokemon/exact/pics2_6e7e_taurospicfront.bin"
                             INCBIN "gfx/pokemon/unused/pics2_7038_7053.bin"
TaurosPicBack::              INCBIN "gfx/pokemon/back/taurosb.pic"
FarfetchdPicFront::          INCBIN "gfx/pokemon/exact/pics2_70e9_farfetchdpicfront.bin"
                             INCBIN "gfx/pokemon/unused/pics2_7259_72c5.bin"
FarfetchdPicBack::           INCBIN "gfx/pokemon/exact/pics2_72c6_farfetchdpicback.bin"
                             INCBIN "gfx/pokemon/unused/pics2_7356_7356.bin"
VenonatPicFront::            INCBIN "gfx/pokemon/exact/pics2_7357_venonatpicfront.bin"
                             INCBIN "gfx/pokemon/unused/pics2_7425_745b.bin"
VenonatPicBack::             INCBIN "gfx/pokemon/back/venonatb.pic"
MoltresPicFront::            INCBIN "gfx/pokemon/exact/pics2_74aa_moltrespicfront.bin"
                             INCBIN "gfx/pokemon/unused/pics2_767a_767e.bin"
DragonitePicBack::           INCBIN "gfx/pokemon/exact/pics2_767f_dragonitepicback.bin"
                             INCBIN "gfx/pokemon/unused/pics2_772b_772b.bin"
DoduoPicFront::              INCBIN "gfx/pokemon/exact/pics2_772c_doduopicfront.bin"
                             INCBIN "gfx/pokemon/unused/pics2_780c_780c.bin"
DoduoPicBack::               INCBIN "gfx/pokemon/back/doduob.pic"
PoliwagPicFront::            INCBIN "gfx/pokemon/exact/pics2_7875_poliwagpicfront.bin"
                             INCBIN "gfx/pokemon/unused/pics2_792e_7946.bin"
PoliwagPicBack::             INCBIN "gfx/pokemon/exact/pics2_7947_poliwagpicback.bin"
                             INCBIN "gfx/pokemon/unused/pics2_798d_798d.bin"
JynxPicFront::               INCBIN "gfx/pokemon/front/jynx.pic"
                             INCBIN "gfx/pokemon/unused/pics2_7b37_7b41.bin"
JynxPicBack::                INCBIN "gfx/pokemon/exact/pics2_7b42_jynxpicback.bin"
                             INCBIN "gfx/pokemon/unused/pics2_7baa_7bab.bin"
DragonitePicFront::          INCBIN "gfx/pokemon/exact/pics2_7bac_dragonitepicfront.bin"
                             INCBIN "gfx/pokemon/unused/pics2_7dc2_7e01.bin"
MoltresPicBack::             INCBIN "gfx/pokemon/back/moltresb.pic"



SECTION "Pics 3", ROMX

ArticunoPicFront:: INCBIN "gfx/pokemon/exact/pics3_4000_articunopicfront.bin"
ArticunoPicBack:: INCBIN "gfx/pokemon/exact/pics3_4238_articunopicback.bin"
ZapdosPicFront:: INCBIN "gfx/pokemon/exact/pics3_429d_zapdospicfront.bin"
ZapdosPicBack:: INCBIN "gfx/pokemon/exact/pics3_4484_zapdospicback.bin"
DittoPicFront:: INCBIN "gfx/pokemon/exact/pics3_4514_dittopicfront.bin"
DittoPicBack:: INCBIN "gfx/pokemon/exact/pics3_45bd_dittopicback.bin"
MeowthPicFront:: INCBIN "gfx/pokemon/exact/pics3_4609_meowthpicfront.bin"
MeowthPicBack:: INCBIN "gfx/pokemon/exact/pics3_471f_meowthpicback.bin"
KrabbyPicFront:: INCBIN "gfx/pokemon/exact/pics3_4777_krabbypicfront.bin"
KrabbyPicBack:: INCBIN "gfx/pokemon/exact/pics3_48b0_krabbypicback.bin"
VulpixPicFront:: INCBIN "gfx/pokemon/exact/pics3_4924_vulpixpicfront.bin"
VulpixPicBack:: INCBIN "gfx/pokemon/exact/pics3_4a9a_vulpixpicback.bin"
NinetalesPicFront:: INCBIN "gfx/pokemon/exact/pics3_4aff_ninetalespicfront.bin"
NinetalesPicBack:: INCBIN "gfx/pokemon/exact/pics3_4cfb_ninetalespicback.bin"
PikachuPicFront:: INCBIN "gfx/pokemon/exact/pics3_4d7d_pikachupicfront.bin"
PikachuPicBack:: INCBIN "gfx/pokemon/exact/pics3_4e8b_pikachupicback.bin"
RaichuPicFront:: INCBIN "gfx/pokemon/exact/pics3_4f03_raichupicfront.bin"
RaichuPicBack:: INCBIN "gfx/pokemon/exact/pics3_50c3_raichupicback.bin"
DratiniPicFront:: INCBIN "gfx/pokemon/exact/pics3_5151_dratinipicfront.bin"
DratiniPicBack:: INCBIN "gfx/pokemon/exact/pics3_5234_dratinipicback.bin"
DragonairPicFront:: INCBIN "gfx/pokemon/exact/pics3_5297_dragonairpicfront.bin"
DragonairPicBack:: INCBIN "gfx/pokemon/exact/pics3_53d9_dragonairpicback.bin"
KabutoPicFront:: INCBIN "gfx/pokemon/exact/pics3_5464_kabutopicfront.bin"
KabutoPicBack:: INCBIN "gfx/pokemon/exact/pics3_5529_kabutopicback.bin"
KabutopsPicFront:: INCBIN "gfx/pokemon/exact/pics3_5583_kabutopspicfront.bin"
KabutopsPicBack:: INCBIN "gfx/pokemon/exact/pics3_573c_kabutopspicback.bin"
HorseaPicFront:: INCBIN "gfx/pokemon/exact/pics3_57c1_horseapicfront.bin"
HorseaPicBack:: INCBIN "gfx/pokemon/exact/pics3_5873_horseapicback.bin"
SeadraPicFront:: INCBIN "gfx/pokemon/exact/pics3_58c4_seadrapicfront.bin"
SeadraPicBack:: INCBIN "gfx/pokemon/exact/pics3_5a2b_seadrapicback.bin"
SandshrewPicFront:: INCBIN "gfx/pokemon/exact/pics3_5ac9_sandshrewpicfront.bin"
SandshrewPicBack:: INCBIN "gfx/pokemon/exact/pics3_5be7_sandshrewpicback.bin"
SandslashPicFront:: INCBIN "gfx/pokemon/exact/pics3_5c6b_sandslashpicfront.bin"
SandslashPicBack:: INCBIN "gfx/pokemon/exact/pics3_5e04_sandslashpicback.bin"
OmanytePicFront:: INCBIN "gfx/pokemon/exact/pics3_5e9d_omanytepicfront.bin"
OmanytePicBack:: INCBIN "gfx/pokemon/exact/pics3_5f76_omanytepicback.bin"
OmastarPicFront:: INCBIN "gfx/pokemon/exact/pics3_5fd3_omastarpicfront.bin"
OmastarPicBack:: INCBIN "gfx/pokemon/exact/pics3_618b_omastarpicback.bin"
JigglypuffPicFront:: INCBIN "gfx/pokemon/exact/pics3_622f_jigglypuffpicfront.bin"
JigglypuffPicBack:: INCBIN "gfx/pokemon/exact/pics3_630f_jigglypuffpicback.bin"
WigglytuffPicFront:: INCBIN "gfx/pokemon/exact/pics3_6348_wigglytuffpicfront.bin"
WigglytuffPicBack:: INCBIN "gfx/pokemon/exact/pics3_64bf_wigglytuffpicback.bin"
EeveePicFront:: INCBIN "gfx/pokemon/exact/pics3_6531_eeveepicfront.bin"
EeveePicBack:: INCBIN "gfx/pokemon/exact/pics3_6625_eeveepicback.bin"
VaporeonPicFront:: INCBIN "gfx/pokemon/exact/pics3_668d_vaporeonpicfront.bin"
FlareonPicBack:: INCBIN "gfx/pokemon/exact/pics3_6806_flareonpicback.bin"
JolteonPicFront:: INCBIN "gfx/pokemon/exact/pics3_688f_jolteonpicfront.bin"
JolteonPicBack:: INCBIN "gfx/pokemon/exact/pics3_6a0a_jolteonpicback.bin"
FlareonPicFront:: INCBIN "gfx/pokemon/exact/pics3_6aae_flareonpicfront.bin"
VaporeonPicBack:: INCBIN "gfx/pokemon/exact/pics3_6c02_vaporeonpicback.bin"
MachopPicFront:: INCBIN "gfx/pokemon/exact/pics3_6c9f_machoppicfront.bin"
MachopPicBack:: INCBIN "gfx/pokemon/exact/pics3_6da2_machoppicback.bin"
ZubatPicFront:: INCBIN "gfx/pokemon/exact/pics3_6e0c_zubatpicfront.bin"
ZubatPicBack:: INCBIN "gfx/pokemon/exact/pics3_6f17_zubatpicback.bin"
EkansPicFront:: INCBIN "gfx/pokemon/exact/pics3_6f6b_ekanspicfront.bin"
EkansPicBack:: INCBIN "gfx/pokemon/exact/pics3_706d_ekanspicback.bin"
ParasPicFront:: INCBIN "gfx/pokemon/exact/pics3_70b4_paraspicfront.bin"
ParasPicBack:: INCBIN "gfx/pokemon/exact/pics3_7177_paraspicback.bin"
PoliwhirlPicFront:: INCBIN "gfx/pokemon/exact/pics3_71ed_poliwhirlpicfront.bin"
PoliwhirlPicBack:: INCBIN "gfx/pokemon/exact/pics3_735e_poliwhirlpicback.bin"
PoliwrathPicFront:: INCBIN "gfx/pokemon/exact/pics3_73c1_poliwrathpicfront.bin"
PoliwrathPicBack:: INCBIN "gfx/pokemon/exact/pics3_752c_poliwrathpicback.bin"
WeedlePicFront:: INCBIN "gfx/pokemon/exact/pics3_757d_weedlepicfront.bin"
WeedlePicBack:: INCBIN "gfx/pokemon/exact/pics3_7624_weedlepicback.bin"
KakunaPicFront:: INCBIN "gfx/pokemon/exact/pics3_7677_kakunapicfront.bin"
KakunaPicBack:: INCBIN "gfx/pokemon/exact/pics3_7736_kakunapicback.bin"
BeedrillPicFront:: INCBIN "gfx/pokemon/exact/pics3_7788_beedrillpicfront.bin"
BeedrillPicBack:: INCBIN "gfx/pokemon/exact/pics3_7980_beedrillpicback.bin"
FossilKabutopsPic:: INCBIN "gfx/pokemon/exact/pics3_79e8_fossilkabutopspic.bin"


SECTION "Pics 4", ROMX

VenomothPicFront:: INCBIN "gfx/pokemon/exact/pics4_4000_venomothpicfront.bin"
DodrioPicBack:: INCBIN "gfx/pokemon/exact/pics4_41a2_dodriopicback.bin"
PrimeapePicFront:: INCBIN "gfx/pokemon/exact/pics4_4247_primeapepicfront.bin"
PrimeapePicBack:: INCBIN "gfx/pokemon/exact/pics4_4408_primeapepicback.bin"
DugtrioPicFront:: INCBIN "gfx/pokemon/exact/pics4_4480_dugtriopicfront.bin"
DugtrioPicBack:: INCBIN "gfx/pokemon/exact/pics4_462a_dugtriopicback.bin"
GolbatPicFront:: INCBIN "gfx/pokemon/exact/pics4_46a9_golbatpicfront.bin"
VenomothPicBack:: INCBIN "gfx/pokemon/exact/pics4_4841_venomothpicback.bin"
DewgongPicFront:: INCBIN "gfx/pokemon/exact/pics4_4899_dewgongpicfront.bin"
DewgongPicBack:: INCBIN "gfx/pokemon/exact/pics4_49e2_dewgongpicback.bin"
CaterpiePicFront:: INCBIN "gfx/pokemon/exact/pics4_4a49_caterpiepicfront.bin"
CaterpiePicBack:: INCBIN "gfx/pokemon/exact/pics4_4ae1_caterpiepicback.bin"
MetapodPicFront:: INCBIN "gfx/pokemon/exact/pics4_4b3a_metapodpicfront.bin"
MetapodPicBack:: INCBIN "gfx/pokemon/exact/pics4_4bc8_metapodpicback.bin"
ButterfreePicFront:: INCBIN "gfx/pokemon/exact/pics4_4c37_butterfreepicfront.bin"
ButterfreePicBack:: INCBIN "gfx/pokemon/exact/pics4_4e0e_butterfreepicback.bin"
MachampPicFront:: INCBIN "gfx/pokemon/exact/pics4_4e93_machamppicfront.bin"
MachampPicBack:: INCBIN "gfx/pokemon/exact/pics4_508c_machamppicback.bin"
GolduckPicFront:: INCBIN "gfx/pokemon/exact/pics4_5108_golduckpicfront.bin"
GolduckPicBack:: INCBIN "gfx/pokemon/exact/pics4_52c2_golduckpicback.bin"
HypnoPicFront:: INCBIN "gfx/pokemon/exact/pics4_535d_hypnopicfront.bin"
HypnoPicBack:: INCBIN "gfx/pokemon/exact/pics4_5552_hypnopicback.bin"
DodrioPicFront:: INCBIN "gfx/pokemon/exact/pics4_55e0_dodriopicfront.bin"
GolbatPicBack:: INCBIN "gfx/pokemon/exact/pics4_580a_golbatpicback.bin"
MewtwoPicFront:: INCBIN "gfx/pokemon/exact/pics4_587f_mewtwopicfront.bin"
MewtwoPicBack:: INCBIN "gfx/pokemon/exact/pics4_5a85_mewtwopicback.bin"
SnorlaxPicFront:: INCBIN "gfx/pokemon/exact/pics4_5b19_snorlaxpicfront.bin"
SnorlaxPicBack:: INCBIN "gfx/pokemon/exact/pics4_5ce5_snorlaxpicback.bin"
MagikarpPicFront:: INCBIN "gfx/pokemon/exact/pics4_5d31_magikarppicfront.bin"
MagikarpPicBack:: INCBIN "gfx/pokemon/exact/pics4_5ec3_magikarppicback.bin"
MukPicFront:: INCBIN "gfx/pokemon/exact/pics4_5f56_mukpicfront.bin"
MukPicBack:: INCBIN "gfx/pokemon/exact/pics4_615f_mukpicback.bin"
KinglerPicFront:: INCBIN "gfx/pokemon/exact/pics4_61ec_kinglerpicfront.bin"
KinglerPicBack:: INCBIN "gfx/pokemon/exact/pics4_63de_kinglerpicback.bin"
CloysterPicFront:: INCBIN "gfx/pokemon/exact/pics4_647f_cloysterpicfront.bin"
CloysterPicBack:: INCBIN "gfx/pokemon/exact/pics4_66ab_cloysterpicback.bin"
ElectrodePicFront:: INCBIN "gfx/pokemon/exact/pics4_6760_electrodepicfront.bin"
ElectrodePicBack:: INCBIN "gfx/pokemon/exact/pics4_6827_electrodepicback.bin"
ClefablePicFront:: INCBIN "gfx/pokemon/exact/pics4_688c_clefablepicfront.bin"
ClefablePicBack:: INCBIN "gfx/pokemon/exact/pics4_69b8_clefablepicback.bin"
WeezingPicFront:: INCBIN "gfx/pokemon/exact/pics4_6a44_weezingpicfront.bin"
WeezingPicBack:: INCBIN "gfx/pokemon/exact/pics4_6c76_weezingpicback.bin"
PersianPicFront:: INCBIN "gfx/pokemon/exact/pics4_6d1e_persianpicfront.bin"
PersianPicBack:: INCBIN "gfx/pokemon/exact/pics4_6f04_persianpicback.bin"
MarowakPicFront:: INCBIN "gfx/pokemon/exact/pics4_6f8f_marowakpicfront.bin"
MarowakPicBack:: INCBIN "gfx/pokemon/exact/pics4_7101_marowakpicback.bin"
HaunterPicFront:: INCBIN "gfx/pokemon/exact/pics4_718a_haunterpicfront.bin"
HaunterPicBack:: INCBIN "gfx/pokemon/exact/pics4_7345_haunterpicback.bin"
AbraPicFront:: INCBIN "gfx/pokemon/exact/pics4_73cc_abrapicfront.bin"
AbraPicBack:: INCBIN "gfx/pokemon/exact/pics4_74cf_abrapicback.bin"
AlakazamPicFront:: INCBIN "gfx/pokemon/exact/pics4_755a_alakazampicfront.bin"
AlakazamPicBack:: INCBIN "gfx/pokemon/exact/pics4_7779_alakazampicback.bin"
PidgeottoPicFront:: INCBIN "gfx/pokemon/exact/pics4_780a_pidgeottopicfront.bin"
PidgeottoPicBack:: INCBIN "gfx/pokemon/exact/pics4_795b_pidgeottopicback.bin"
PidgeotPicFront:: INCBIN "gfx/pokemon/exact/pics4_79c2_pidgeotpicfront.bin"
PidgeotPicBack:: INCBIN "gfx/pokemon/exact/pics4_7b79_pidgeotpicback.bin"
StarmiePicFront:: INCBIN "gfx/pokemon/exact/pics4_7c1c_starmiepicfront.bin"
StarmiePicBack:: INCBIN "gfx/pokemon/exact/pics4_7dac_starmiepicback.bin"
RedPicBack:: INCBIN "gfx/pokemon/exact/pics4_7e0a_redpicback.bin"
OldManPicBack:: INCBIN "gfx/pokemon/exact/pics4_7e9a_oldmanpicback.bin"



SECTION "Pics 5", ROMX

BulbasaurPicFront:: INCBIN "gfx/pokemon/exact/pics5_4000_bulbasaurpicfront.bin"
BulbasaurPicBack:: INCBIN "gfx/pokemon/exact/pics5_40e5_bulbasaurpicback.bin"
VenusaurPicFront:: INCBIN "gfx/pokemon/exact/pics5_4162_venusaurpicfront.bin"
VenusaurPicBack:: INCBIN "gfx/pokemon/exact/pics5_4397_venusaurpicback.bin"
TentacruelPicFront:: INCBIN "gfx/pokemon/exact/pics5_4455_tentacruelpicfront.bin"
TentacruelPicBack:: INCBIN "gfx/pokemon/exact/pics5_45c3_tentacruelpicback.bin"
GoldeenPicFront:: INCBIN "gfx/pokemon/exact/pics5_466f_goldeenpicfront.bin"
GoldeenPicBack:: INCBIN "gfx/pokemon/exact/pics5_4796_goldeenpicback.bin"
SeakingPicFront:: INCBIN "gfx/pokemon/exact/pics5_4803_seakingpicfront.bin"
SeakingPicBack:: INCBIN "gfx/pokemon/exact/pics5_4a03_seakingpicback.bin"
PonytaPicFront:: INCBIN "gfx/pokemon/exact/pics5_4ab1_ponytapicfront.bin"
RapidashPicFront:: INCBIN "gfx/pokemon/exact/pics5_4c10_rapidashpicfront.bin"
PonytaPicBack:: INCBIN "gfx/pokemon/exact/pics5_4e32_ponytapicback.bin"
RapidashPicBack:: INCBIN "gfx/pokemon/exact/pics5_4eba_rapidashpicback.bin"
RattataPicFront:: INCBIN "gfx/pokemon/exact/pics5_4f6a_rattatapicfront.bin"
RattataPicBack:: INCBIN "gfx/pokemon/exact/pics5_5041_rattatapicback.bin"
RaticatePicFront:: INCBIN "gfx/pokemon/exact/pics5_507a_raticatepicfront.bin"
RaticatePicBack:: INCBIN "gfx/pokemon/exact/pics5_520d_raticatepicback.bin"
NidorinoPicFront:: INCBIN "gfx/pokemon/exact/pics5_5282_nidorinopicfront.bin"
NidorinoPicBack:: INCBIN "gfx/pokemon/exact/pics5_53f0_nidorinopicback.bin"
NidorinaPicFront:: INCBIN "gfx/pokemon/exact/pics5_548b_nidorinapicfront.bin"
NidorinaPicBack:: INCBIN "gfx/pokemon/exact/pics5_55c8_nidorinapicback.bin"
GeodudePicFront:: INCBIN "gfx/pokemon/exact/pics5_564f_geodudepicfront.bin"
GeodudePicBack:: INCBIN "gfx/pokemon/exact/pics5_5729_geodudepicback.bin"
PorygonPicFront:: INCBIN "gfx/pokemon/exact/pics5_5784_porygonpicfront.bin"
PorygonPicBack:: INCBIN "gfx/pokemon/exact/pics5_58d1_porygonpicback.bin"
AerodactylPicFront:: INCBIN "gfx/pokemon/exact/pics5_5931_aerodactylpicfront.bin"
AerodactylPicBack:: INCBIN "gfx/pokemon/exact/pics5_5aec_aerodactylpicback.bin"
MagnemitePicFront:: INCBIN "gfx/pokemon/exact/pics5_5b87_magnemitepicfront.bin"
MagnemitePicBack:: INCBIN "gfx/pokemon/exact/pics5_5c0d_magnemitepicback.bin"
CharmanderPicFront:: INCBIN "gfx/pokemon/exact/pics5_5c5c_charmanderpicfront.bin"
CharmanderPicBack:: INCBIN "gfx/pokemon/exact/pics5_5d5c_charmanderpicback.bin"
SquirtlePicFront:: INCBIN "gfx/pokemon/exact/pics5_5db8_squirtlepicfront.bin"
SquirtlePicBack:: INCBIN "gfx/pokemon/exact/pics5_5e8f_squirtlepicback.bin"
CharmeleonPicFront:: INCBIN "gfx/pokemon/exact/pics5_5f0c_charmeleonpicfront.bin"
CharmeleonPicBack:: INCBIN "gfx/pokemon/exact/pics5_6048_charmeleonpicback.bin"
WartortlePicFront:: INCBIN "gfx/pokemon/exact/pics5_60b1_wartortlepicfront.bin"
WartortlePicBack:: INCBIN "gfx/pokemon/exact/pics5_61f1_wartortlepicback.bin"
CharizardPicFront:: INCBIN "gfx/pokemon/exact/pics5_6286_charizardpicfront.bin"
CharizardPicBack:: INCBIN "gfx/pokemon/exact/pics5_6495_charizardpicback.bin"
FossilAerodactylPic:: INCBIN "gfx/pokemon/exact/pics5_6536_fossilaerodactylpic.bin"
GhostPic:: INCBIN "gfx/pokemon/exact/pics5_66b5_ghostpic.bin"
OddishPicFront:: INCBIN "gfx/pokemon/exact/pics5_680b_oddishpicfront.bin"
OddishPicBack:: INCBIN "gfx/pokemon/exact/pics5_68a9_oddishpicback.bin"
GloomPicFront:: INCBIN "gfx/pokemon/exact/pics5_6941_gloompicfront.bin"
GloomPicBack:: INCBIN "gfx/pokemon/exact/pics5_6a78_gloompicback.bin"
VileplumePicFront:: INCBIN "gfx/pokemon/exact/pics5_6b21_vileplumepicfront.bin"
VileplumePicBack:: INCBIN "gfx/pokemon/exact/pics5_6c82_vileplumepicback.bin"
BellsproutPicFront:: INCBIN "gfx/pokemon/exact/pics5_6d00_bellsproutpicfront.bin"
BellsproutPicBack:: INCBIN "gfx/pokemon/exact/pics5_6dba_bellsproutpicback.bin"
WeepinbellPicFront:: INCBIN "gfx/pokemon/exact/pics5_6e30_weepinbellpicfront.bin"
WeepinbellPicBack:: INCBIN "gfx/pokemon/exact/pics5_6f6f_weepinbellpicback.bin"
VictreebelPicFront:: INCBIN "gfx/pokemon/exact/pics5_6fea_victreebelpicfront.bin"
VictreebelPicBack:: INCBIN "gfx/pokemon/exact/pics5_71b2_victreebelpicback.bin"



SECTION "Trainer Pics", ROMX

YoungsterPic::     INCBIN "gfx/trainers/youngster.pic"
BugCatcherPic::    INCBIN "gfx/trainers/bugcatcher.pic"
LassPic::          INCBIN "gfx/trainers/lass.pic"
SailorPic::        INCBIN "gfx/trainers/sailor.pic"
JrTrainerMPic::    INCBIN "gfx/trainers/jr.trainerm.pic"
JrTrainerFPic::    INCBIN "gfx/trainers/jr.trainerf.pic"
PokemaniacPic::    INCBIN "gfx/trainers/pokemaniac.pic"
SuperNerdPic::     INCBIN "gfx/trainers/supernerd.pic"
HikerPic::         INCBIN "gfx/trainers/hiker.pic"
BikerPic::         INCBIN "gfx/trainers/biker.pic"
BurglarPic::       INCBIN "gfx/trainers/burglar.pic"
EngineerPic::      INCBIN "gfx/trainers/engineer.pic"
                  INCBIN "gfx/trainers/unused_after_engineer.bin"
FisherPic::        INCBIN "gfx/trainers/fisher.pic"
SwimmerPic::       INCBIN "gfx/trainers/swimmer.pic"
CueBallPic::       INCBIN "gfx/trainers/cueball.pic"
GamblerPic::       INCBIN "gfx/trainers/gambler.pic"
BeautyPic::        INCBIN "gfx/trainers/beauty.pic"
PsychicPic::       INCBIN "gfx/trainers/psychic.pic"
RockerPic::        INCBIN "gfx/trainers/rocker.pic"
JugglerPic::       INCBIN "gfx/trainers/juggler.pic"
TamerPic::         INCBIN "gfx/trainers/tamer.pic"
BirdKeeperPic::    INCBIN "gfx/trainers/birdkeeper.pic"
BlackbeltPic::     INCBIN "gfx/trainers/blackbelt.pic"
Rival1Pic::        INCBIN "gfx/trainers/rival1.pic"
ProfOakPic::       INCBIN "gfx/trainers/prof.oak.pic"
ChiefPic::
ScientistPic::     INCBIN "gfx/trainers/scientist.pic"
GiovanniPic::      INCBIN "gfx/trainers/giovanni.pic"
                  INCBIN "gfx/trainers/unused_after_giovanni.bin"
RocketPic::        INCBIN "gfx/trainers/rocket.pic"
CooltrainerMPic::  INCBIN "gfx/trainers/cooltrainerm.pic"
CooltrainerFPic::  INCBIN "gfx/trainers/cooltrainerf.pic"
BrunoPic::         INCBIN "gfx/trainers/bruno.pic"
                  INCBIN "gfx/trainers/unused_after_bruno.bin"
BrockPic::         INCBIN "gfx/trainers/brock.pic"
                  INCBIN "gfx/trainers/unused_after_brock.bin"
MistyPic::         INCBIN "gfx/trainers/misty.pic"
                  INCBIN "gfx/trainers/unused_after_misty.bin"
LtSurgePic::       INCBIN "gfx/trainers/lt.surge.pic"
                  INCBIN "gfx/trainers/unused_after_lt.surge.bin"
ErikaPic::         INCBIN "gfx/trainers/erika.pic"
                  INCBIN "gfx/trainers/unused_after_erika.bin"
KogaPic::          INCBIN "gfx/trainers/koga.pic"
                  INCBIN "gfx/trainers/unused_after_koga.bin"
BlainePic::        INCBIN "gfx/trainers/blaine.pic"
                  INCBIN "gfx/trainers/unused_after_blaine.bin"
SabrinaPic::       INCBIN "gfx/trainers/sabrina.pic"
                  INCBIN "gfx/trainers/unused_after_sabrina.bin"
GentlemanPic::     INCBIN "gfx/trainers/gentleman.pic"
Rival2Pic::        INCBIN "gfx/trainers/rival2.pic"
Rival3Pic::        INCBIN "gfx/trainers/rival3.pic"
LoreleiPic::       INCBIN "gfx/trainers/lorelei.pic"
ChannelerPic::     INCBIN "gfx/trainers/channeler.pic"
AgathaPic::        INCBIN "gfx/trainers/agatha.pic"
LancePic::         INCBIN "gfx/trainers/lance.pic"
                  INCBIN "gfx/trainers/unused_after_lance.bin"