_LancesRoomLanceBeforeBattleText::
	text "So you managed to"
	line "beat my DAD, and"
	cont "even CALIGULA."
	para "After what he"
	line "did to my great"
	cont "grandfather, DAD"
	cont "and I vowed to"
	cont "become stronger."
	para "You are very"
	line "strong, <PLAYER>."
	para "But now you are"
	line "up against the"
	cont "WORLD CHAMPION of"
	cont "the #MON"
	cont "LEAGUE."
	para "<PLAYER>, I'm sorry"
	line "to say, but your"
	cont "quest ends!"
	para "VOICE: Let the"
	line "Semi-Finals,"
	para "BEGIN!"
	done

_LancesRoomLanceEndBattleText::
	text "It's over..."
	para "VOICE: And the"
	line "winner is <PLAYER>!"
	cont "Congratulations!"
	prompt

_LancesRoomLanceAfterBattleText::
	text "VOICE: <PLAYER>"
	line "will proceed to"
	cont "the finals."
	para "OKIDO: Noisy"
	line "announcer. Well"
	cont "done <PLAYER>."
	para "Your quest is"
	line "almost over."
	para "This is your last"
	line "chance to prepare"
	cont "yourself."
	para "Once you enter,"
	line "your quest will"
	cont "end..."
	para "But do not fear."
	para "No matter what"
	line "awaits you within"
	cont "the last room..."
	para "Believe in your"
	line "#MON <PLAYER>.@"
	text_end

